name: 'chromatic'
on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run lerna:bootstrap
      - run: npm run build-storybook
      - uses: chromaui/action@v1
        with: 
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: storybook-static
